<a href="https://colab.research.google.com/github/mohitsharmas97/ML_notebooks/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0,1:3])
print(arr[1])

[20 30]
[70 80]


In [ ]:
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr)) #dimension
print(arr.dtype)

(2, 4)
8
2
int64


Inspecting an array


In [ ]:
a=[30,40,30],[40,30,10];
arr=np.array(a)
print(arr)
print(arr.shape)
print(len(arr))
print(np.size(arr))
print(type(arr))
print(arr.dtype)
print(arr.astype(float))

[[30 40 30]
 [40 30 10]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int64
[[30. 40. 30.]
 [40. 30. 10.]]


Mathematical operations and functions on arrays


In [ ]:
arr1=np.array([30,40,10,10])
arr2=np.array([10,20,30,40])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[40 60 40 50]
[ 20  20 -20 -30]
[300 800 300 400]
[3.         2.         0.33333333 0.25      ]


In [ ]:
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))

[40 60 40 50]
[ 20  20 -20 -30]


In [ ]:
arr1=np.array([3,4,2,1])
arr2=np.array([2])
print(np.power(arr1,arr2))


[ 9 16  4  1]


In [ ]:
arr1=np.array([9,16,4,1])
print(np.sqrt(arr1))

[3. 4. 2. 1.]


Combining and Splitting


In [ ]:
 a=[12,4,5]
 b=[3,4,5]
 print(a+b)

[12, 4, 5, 3, 4, 5]


In [ ]:
import numpy as np
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])
# arr=np.concatenate((arr1,arr2))
# print(arr)

In [ ]:
print(np.hstack([ar1,ar2])) #horizontal concatenation

[1 2 3 4 5 6]


In [ ]:
print(np.vstack([ar1,ar2]))  #vertical concatenantion

[[1 2 3]
 [4 5 6]]


In [ ]:
p=np.array([1,2,3,4,5,6])
print(np.array_split(p,4))

[array([1, 2]), array([3, 4]), array([5]), array([6])]


adding and removing elements in an array


In [ ]:
import numpy as np

l=np.array([1,2,3,4])
print(np.append(l,[5,6]))

[1 2 3 4 5 6]


In [ ]:
print(np.insert(l,1,10)) #array,index,val

[ 1 10  2  3  4]


In [ ]:
print(np.delete(l,2))

[1 2 4]


sort ,filter and search


In [ ]:
k=np.array([2,3,1,8])
# print(np.sort(k))

# s=np.where(k==8)
# print(s)

# ss=np.searchsorted(k,4)
# print(ss)

# fa=[True,False,True,False]
# print(k[fa])



NameError: name 'np' is not defined

Aggregate functions in numpy

In [ ]:
c=np.array([20,40,60])
print(np.sum(c))
print(np.min(c))
print(np.max(c))
print(np.mean(c))
print(np.size(c))
print(np.median(c))
print(np.cumsum(c))
print(np.cumprod(c))


120
20
60
40.0
3
40.0
[ 20  60 120]
[   20   800 48000]


Statistical Functions Numpy


In [ ]:
import statistics as stats
baked_food=[200,300,150,130,200,280,170,188]
a1=np.array(baked_food)
print(np.mean(baked_food)) #sum of all values divided by no of values
print(np.median(baked_food)) #centre value after sorting --median
print(stats.mode(baked_food)) #more occuring value
print(np.std(baked_food))

202.25
194.0
200
55.68157235567257


In [ ]:
# -1 represents inversely proportional relationship
# 1 represents proportional relationship
# 0 means no relationship
tobacco_consumption=[30,20,50,10,40]
deaths=[100,120,70,100,12]
print(np.corrcoef([tobacco_consumption,deaths]))

[[ 1.         -0.62946518]
 [-0.62946518  1.        ]]
